"""
Keymap compartilhado entre as duas metades do teclado.

Este arquivo precisa ser copiado para AMBOS os Pico (esquerdo e direito),
junto com o code.py de cada lado. O KMK funde o scan das duas metades
em uma única matriz virtual, então as duas placas precisam carregar
exatamente o mesmo keymap para a leiaute ficar consistente.

Layout: 4 rows x 12 cols (6 cols por metade, fundidas pelo Split).
Layer 0 = base | Layer 1 (TOP) = simbolos/numeros | Layer 2 (LOWER) = setas
"""

from kmk.keys import KC

TOP = KC.MO(1)
LOWER = KC.MO(2)

keymap = [
    # Layer 0 - base
    [
        KC.TAB,
        KC.Q,
        KC.W,
        KC.E,
        KC.R,
        KC.T,
        KC.Y,
        KC.U,
        KC.I,
        KC.O,
        KC.P,
        KC.BKDL,
        KC.LCTRL,
        KC.A,
        KC.S,
        KC.D,
        KC.F,
        KC.G,
        KC.H,
        KC.J,
        KC.K,
        KC.L,
        KC.SCLN,
        KC.QUOT,
        KC.LSHIFT,
        KC.Z,
        KC.X,
        KC.C,
        KC.V,
        KC.B,
        KC.N,
        KC.M,
        KC.COMM,
        KC.DOT,
        KC.SLSH,
        KC.ESC,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.LGUI,
        TOP,
        KC.SPACE,
        KC.ENTER,
        LOWER,
        KC.LALT,
        KC.NO,
        KC.NO,
        KC.NO,
    ],
    # Layer 1 (TOP) - simbolos e numeros
    [
        KC.TAB,
        KC.EXLM,
        KC.AT,
        KC.HASH,
        KC.DLR,
        KC.PERC,
        KC.CIRC,
        KC.AMPR,
        KC.ASTR,
        KC.LPRN,
        KC.RPRN,
        KC.DEL,
        KC.LCTRL,
        KC.N1,
        KC.N2,
        KC.N3,
        KC.N4,
        KC.N5,
        KC.N6,
        KC.N7,
        KC.N8,
        KC.N9,
        KC.N0,
        KC.NO,
        KC.LSHIFT,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.LBRC,
        KC.RBRC,
        KC.MINS,
        KC.EQL,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.LGUI,
        KC.TRANS,
        KC.SPACE,
        KC.ENTER,
        KC.TRANS,
        KC.LALT,
        KC.NO,
        KC.NO,
        KC.NO,
    ],
    # Layer 2 (LOWER) - navegacao
    [
        KC.TAB,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.LCTRL,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.UP,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.LSHIFT,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.LEFT,
        KC.DOWN,
        KC.RIGHT,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.NO,
        KC.LGUI,
        KC.TRANS,
        KC.SPACE,
        KC.ENTER,
        KC.TRANS,
        KC.LALT,
        KC.NO,
        KC.NO,
        KC.NO,
    ],
]
